### ISSUE TITLE
Only work on the original website that set the shortcut at

### ISSUE THREAD

**Issue by 1IFEnOTG00d** [ronparkdev/shortcut-click-extension#4]
Worked only on the original page that set that shortcut of a specific website
example: if I set the shortcut on "www.ok.com/1" it would only work at that page, then I tried to use the shortcut on "www.ok.com/2" it wouldn't work even though I set that shortcut to "www.ok.com/*" and they have the same layout.

**Comment by 1IFEnOTG00d** [comment]
Only that website only my bad

**Comment by buddyron** [comment]
It's okay :) Have a good day~
